TDI-44686 : potential NPE
Talend/tdi-studio-se pull request #5164
Opened 2020-09-02 11:53 UTC by clesaec

**What is the current behavior?** (You can also link to an open issue here)

Potential NPE pb

**What is the new behavior?**

resolved, tested on studio, seem to work well => more tests with tuj will be done.

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-09-02 16:10 UTC, coheigea requested changes

2020-09-02 16:10 UTC, coheigea commented on main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
> +            incomingEnforcer_<%=cid%>.getCurrentRecord();
This line is missing the assignment: data_<%=cid%> =

2020-09-03 06:26 UTC, clesaec commented on main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
> +            incomingEnforcer_<%=cid%>.getCurrentRecord();
Yes, thanks, correction done.

2020-09-03 07:06 UTC, coheigea approved these changes

2020-10-26 08:59 UTC, merged