fix(TBD-11038): The distribution AMAZON_EMR with the version APACHE_2_4_0_EMR doesn't exist
Talend/tdi-studio-se pull request #5318
Opened 2020-10-08 12:55 UTC by cbadillo1603

…2_4_0_EMR doesn't exist

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-10-09 01:38 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +    private List<String> versionsLabel = versions.stream().map( v -> v.version ).collect(Collectors.toList());
this logic should be in constructor

2020-10-09 01:39 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +        List<ERepositoryObjectType> toReturn = new ArrayList<ERepositoryObjectType>();
if you use lamda expressions then diamond operators should also be available)

2020-10-09 01:44 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +    private List<String> versionsLabel = versions.stream().map( v -> v.version ).collect(Collectors.toList());
I think everything except IMPACTED_COMPONENT_TYPES should be initialized in constructor

2020-10-09 01:44 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +    private final List<String> IMPACTED_COMPONENT_TYPES =
it isn't static but you use UPPER_CASE style, please rename it to lowerCase or make it static

2020-10-09 01:45 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +    private List<String> versionsLabel = versions.stream().map( v -> v.version ).collect(Collectors.toList());
and all variables can be final, so I suggest adding final keyword to all class-level vars where it's possible.

2020-10-09 01:46 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +        public void transform(NodeType node) {
Is @ Override annotation missed?

2020-10-09 01:47 UTC, amedvedenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +        String DEFAULT_VERSION = versionsLabel.get(0);
.get(0) seems to be not safe, I suggest moving it to constructor. 
Also, what's happened with variable names? :D

2020-10-09 08:12 UTC, cbadillo1603 commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +    private final List<String> IMPACTED_COMPONENT_TYPES =
uppercase names are reserved for final (constant) variables

2020-10-09 08:55 UTC, cbadillo1603 commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/spark/UpdateRemovedHadoopVersion.java
> +        String DEFAULT_VERSION = versionsLabel.get(0);
Even when .get(0) is not safe we need to get a valid distribution from this list. In the remote case where it is empty would mean the whole distribution retrieval module has a problem (Unlikely). So there is no need to invest more effort on making it empty safe.

2020-10-09 09:22 UTC, amedvedenko approved these changes

2020-10-10 03:29 UTC, nrousseau requested changes

2020-10-10 03:29 UTC, nrousseau commented on main/plugins/org.talend.repository/META-INF/MANIFEST.MF
> + org.talend.hadoop.distribution
Can't add the hadoop as required here.
BD / hadoop must be optional at this point, and not a required in the base product.

But note that migration tasks can be added in any plugin. (doesn't need to be all in the same..)

2020-10-12 07:36 UTC, cbadillo1603 commented on main/plugins/org.talend.repository/META-INF/MANIFEST.MF
> + org.talend.hadoop.distribution
Noted, the migration code will be moved to tbd-studio-ee/main/plugins/org.talend.designer.spark/src/org/talend/designer/spark/repository/migration I will close this pull request as is not required any more.

2020-10-12 07:37 UTC, cbadillo1603 commented
the migration code will be moved to tbd-studio-ee/main/plugins/org.talend.designer.spark/src/org/talend/designer/spark/repository/migration Closing this pull request as is not required any more.

2020-10-12 07:37 UTC, closed without merging