feat(TDI-44915) access token feature
Talend/tdi-studio-se pull request #5473
Opened 2020-11-05 13:52 UTC by mbasiuk-talend

**What is the current behavior?** (You can also link to an open issue here)
There are only HMAC and Service Account file authentication types.
https://jira.talendforge.org/browse/TDI-44915

**What is the new behavior?**
Provide a new way of OAuth2 Token access.

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [x] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-11-06 15:35 UTC, chmyga requested changes
Some changes are required. Also, we need to find a way to use function for GS components.

2020-11-06 15:35 UTC, chmyga commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +				(new com.google.api.client.auth.oauth2.TokenResponse()).setAccessToken(decryptedAccessToken_<%=cid%>));
Don't we need to update this token from function(if it is set as function) in BigQuery Input?

2020-11-06 15:35 UTC, chmyga commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_begin.javajet
> +    				(new com.google.api.client.auth.oauth2.TokenResponse()).setAccessToken(decryptedAccessToken_<%=cid%>));
For BigQueryOutput this token should be updated as well, I guess.

2020-11-06 15:35 UTC, chmyga commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_begin.javajet
> +    				(new com.google.api.client.auth.oauth2.TokenResponse()).setAccessToken(decryptedAccessToken_<%=cid%>));
Refresh the token from function.

2020-11-06 15:35 UTC, chmyga commented on main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
> +				SHOW_IF="((AUTH_TYPE == 'SERVICE_ACCOUNT') OR (AUTH_TYPE == 'TOKEN'))"
Why did you remove check from existing connection? it should be shown if existing connection also uses service account authentication(or oauth token as well, I guess).

2020-11-06 15:40 UTC, mbasiuk-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
> +				SHOW_IF="((AUTH_TYPE == 'SERVICE_ACCOUNT') OR (AUTH_TYPE == 'TOKEN'))"
agree. I missed this. Gonna update this.

2020-11-10 09:54 UTC, dmytrogrygorenko approved these changes
LGTM

2020-11-20 10:53 UTC, dmytrogrygorenko approved these changes
Still OK.

2020-11-24 11:36 UTC, dmytrogrygorenko approved these changes

2020-11-26 10:49 UTC, dmytrogrygorenko requested changes

2020-11-26 10:49 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_end.javajet
> +				useHMACAuthType = "USER_ACCOUNT_HMAC".equals(authTypeInConnectionComponent);
Maybe add "break" after this, so no need to iterate further?

2020-11-26 10:49 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_end.javajet
> +                        useHMACAuthType = "USER_ACCOUNT_HMAC".equals(authTypeInConnectionComponent);
Same here.

2020-11-26 10:49 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_end.javajet
> +                        useHMACAuthType = "USER_ACCOUNT_HMAC".equals(authTypeInConnectionComponent);
And here.

2020-11-26 10:57 UTC, mbasiuk-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_end.javajet
> +				useHMACAuthType = "USER_ACCOUNT_HMAC".equals(authTypeInConnectionComponent);
The main idea here was to change conditional property. As you see from the original code that was working before, it doesn't introduce a new issue. As for performance - it won't be even seen. (how many tGSConnection components can be present in the single job?)

2020-11-26 11:08 UTC, dmytrogrygorenko approved these changes
LGTM

2020-11-27 08:04 UTC, merged