fix(TUP-29350): fixed the tMap display issues with Big Sur
Talend/tdi-studio-se pull request #5616
Opened 2020-12-10 06:43 UTC by zyuan-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TUP-29350

**What is the new behavior?**
Use a new way to display on Big Sur.

**Please check if the PR fulfills these requirements**

- [X ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2020-12-10 07:30 UTC, cmeng-talend requested changes

2020-12-10 07:30 UTC, cmeng-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorInfo.java
>          this.blue = blue;
it's better to set the default alpha to 255 here.

2020-12-10 07:30 UTC, cmeng-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorProviderMapper.java
>          colorsCache.put(colorInfo, color);
it's better to add the alpha parameter here, so that we don't need the new method.

2020-12-10 07:30 UTC, cmeng-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorInfo.java
>              return Display.getCurrent().getSystemColor(systemColor).getRGB();
seems there is no caller for this method, but it's better to change the return type from RGB to RGBA

2020-12-11 06:15 UTC, zyuan-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorInfo.java
>          this.blue = blue;
done

2020-12-11 06:23 UTC, zyuan-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorProviderMapper.java
>          colorsCache.put(colorInfo, color);
As discussed, since not sure what's the behavior on Linux platform， in order to not impact the existing invocation, will not modify the existing method and keep this new method.

2020-12-11 06:23 UTC, zyuan-talend commented on main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/color/ColorInfo.java
>              return Display.getCurrent().getSystemColor(systemColor).getRGB();
As discussed, since not sure what's the behavior on Linux platform， in order to not impact the existing invocation, will not modify the existing interface

2020-12-14 01:45 UTC, cmeng-talend approved these changes
LGTM

2020-12-29 02:19 UTC, cmeng-talend approved these changes
LGTM

2020-12-30 08:01 UTC, merged