kjwang/Feat TUP-21090 Support connection component for tacokit
Talend/tdi-studio-se pull request #5977
Opened 2021-03-18 02:33 UTC by kjwang-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TUP-21090

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-04-07 06:49 UTC, cmeng-talend requested changes

2021-04-07 06:49 UTC, cmeng-talend commented on main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
> +        connectionParameter.setDisplayName("Component List");
Maybe need i18n?

2021-04-07 06:49 UTC, cmeng-talend commented on main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
> +            for (int i = 0; i < node.getElementParameters().size(); i++) {
it's better to avoid using list.get(i) here, better to use Iterator or foreach

2021-04-07 06:49 UTC, cmeng-talend commented on main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
> +            for (int i = 0; i < node.getElementParameters().size(); i++) {
it's better to avoid using list.get(i) here, better to use Iterator or foreach

2021-04-07 08:39 UTC, cmeng-talend approved these changes

2021-04-13 09:24 UTC, wchen-talend approved these changes

2021-04-13 10:06 UTC, merged