fix(TDI-46065): Redshift - add "Credential Provider" option to XML layout.
Talend/tdi-studio-se pull request #6207
Opened 2021-05-11 13:57 UTC by dmytrogrygorenko

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-46065

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-11 14:02 UTC, mbasiuk-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_messages.properties
> +CREDENTIAL_PROVIDER.ITEM.WEB_TOKEN=Web Identity token
The only concern for rules for naming, second word is lowercase

2021-05-11 14:04 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_messages.properties
> +CLIENT_CONFIG.NAME=S3 settings
This line a bit unexpected for me. Why do we add it here?

2021-05-11 14:06 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_messages.properties
> +CREDENTIAL_PROVIDER.ITEM.WEB_TOKEN=Web Identity token
Fixed.

2021-05-11 14:53 UTC, ozhelezniak-talend approved these changes
LGTM with minor comment

2021-05-11 14:59 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
> -		<PARAMETER NAME="COMPRESS" FIELD="CHECK" NUM_ROW="20"
Reverted the line number changes.

2021-05-12 12:59 UTC, mbasiuk-talend approved these changes

2021-05-12 20:23 UTC, ozhelezniak-talend reviewed
A few, not mandatory comments. And one question about the fate of the state of  "INHERIT_CREDENTIALS" checkbox.

2021-05-12 20:23 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                if(componentsName[i] == "tRedshiftBulkExec") {
It's better to use "equals" method with String objects

2021-05-12 20:23 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +            IComponentConversion removePropertyComponentConversion = new RemovePropertyComponentConversion("INHERIT_CREDENTIALS");
this object is reused for all components name (one object to many componentName)
the other IComponentConversions ("that adds closed list" and "that set show to false") are created per iteration
(one object to one componentName)

Please, choose homogeneous behavior

2021-05-12 20:23 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                        Arrays.<IComponentConversion> asList(new IComponentConversion() {
When you need a list for a single element it's better to use  "Collections.singletonList()"

2021-05-12 20:23 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                                    ComponentUtilities.addNodeProperty(node, "CREDENTIAL_PROVIDER", "CLOSED_LIST");
Need to discuss this part.
Question.
Why does the state of "INHERIT_CREDENTIALS" checkbox is ignored?
We just remove it and don't care about its state. Is it correct?

2021-05-12 20:24 UTC, ozhelezniak-talend requested changes
Please, look at above comment

2021-05-13 13:53 UTC, ozhelezniak-talend approved these changes
LGTM

2021-05-13 14:33 UTC, dmytrogrygorenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                if(componentsName[i] == "tRedshiftBulkExec") {
Fixed, changed to "equals()".

2021-05-13 14:34 UTC, dmytrogrygorenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +            IComponentConversion removePropertyComponentConversion = new RemovePropertyComponentConversion("INHERIT_CREDENTIALS");
Fixed - RemovePropertyComponentConversion is now being created for each iteration.

2021-05-13 14:35 UTC, dmytrogrygorenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                        Arrays.<IComponentConversion> asList(new IComponentConversion() {
Fixed - changed to "Collections.singletonList()".

2021-05-13 14:36 UTC, dmytrogrygorenko commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                                    ComponentUtilities.addNodeProperty(node, "CREDENTIAL_PROVIDER", "CLOSED_LIST");
Fixed - now state of checkbox is being handled in migration task.

2021-05-14 06:49 UTC, ozhelezniak-talend approved these changes
LGTM

2021-05-14 06:49 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
> +	          <ITEM NAME="WEB_TOKEN" VALUE="WEB_TOKEN" SHOW_IF="true" />
Here we can add either comment that this item won't work without three additional parameters in advanced settings:
WEB_*** or add them into advanced settings.
Or mention these specifics in the Work Item. Because a person who will add this functionality may be confused that we didn't add those three WEB_*** paramaters.

2021-05-14 12:03 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTaskForRedshift.java
> +                                ComponentUtilities.getNodeProperty(node, "CREDENTIAL_PROVIDER").setShow(false);
You can move this line into the previous IComponentConversion.
Maybe even move inside if block to change only created credential provider elements with this migration task

2021-05-14 12:15 UTC, ozhelezniak-talend approved these changes
LGTM

2021-05-14 14:08 UTC, ozhelezniak-talend reviewed
We forget to update the properties file for tRedshiftBulkExec

2021-05-14 14:15 UTC, ozhelezniak-talend approved these changes
LGTM
(BulkExec didn't contain a message for hidden inherit_credentials checkbox. So I think no need to add messages for new hidden element)

2021-06-11 08:13 UTC, merged