Vyu/tdi 45797 s3put enable object lock feature
Talend/tdi-studio-se pull request #6285
Opened 2021-05-28 03:37 UTC by vyu-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45797

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-05-28 03:45 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
> +		String retentionMode_<%=cid %> = "<%=retentionMode %>";
Why convert this variable from javajet into generated code? Does it have a special reason?

2021-05-28 03:53 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
> +		String retentionMode_<%=cid %> = "<%=retentionMode %>";
Just want users can read the code clearly.

2021-05-28 03:58 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
> +		String retentionMode_<%=cid %> = "<%=retentionMode %>";
The customer should rarely read the code. The logic of generate code goes into javajet, in terms of **HIDING** this logic from the customer. less is more.

2021-05-28 08:56 UTC, pyzhou-talend approved these changes
LGTM

2021-06-07 08:51 UTC, pyzhou-talend approved these changes
LGTM

2021-06-08 07:15 UTC, jzhao-talend requested changes
https://github.com/Talend/tdi-studio-se/blob/vyu/TDI-45797_s3put_enable_object_lock_feature/main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_begin.javajet#L92
Your changes would break tS3Copy

2021-06-09 03:17 UTC, merged