feat(TDI-45914): bigquery stored procedures
Talend/tdi-studio-se pull request #6363
Opened 2021-06-25 13:02 UTC by mbasiuk-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45914

**What is the new behavior?**
Return statistics for job executions, implement die on error for SQLRow and Input components. Handle multi result set for Input and SQLRow components.

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-06-28 11:06 UTC, bgunics-talend requested changes
I see a lot of copy-paste for the die on Error  exception /  log.error / System.err messages. I'd prefer to refactor this and maybe use something from ../templates/ WDYT?

2021-06-28 11:06 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +            %>
Maybe would worth to refactor this part so we can avoid copy paste?
Then we could just do it in 1 line:
handleDieOnError( boolean dieOnError, boolean isLog4jEnabled , String message);

I see this pattern a lot in the jobs so it would make sense to have it as a template.

2021-06-28 11:06 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +            }
and here

2021-06-28 11:06 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +                    %>
and here, although the continue; piece have to be moved outside

2021-06-28 11:06 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +        }
and here

2021-06-28 11:06 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +            }
here we're not using System.err like in the other cases?

2021-07-01 22:17 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
> +                com.google.gson.Gson gsonObject = new com.google.gson.Gson();
might be safer to add _<%=cid%> here no?

2021-07-01 22:24 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_main.javajet
> +                com.google.gson.Gson gsonObject = new com.google.gson.Gson();
We should add _<%=cid%>

2021-07-01 22:24 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_main.javajet
> +                com.google.gson.Gson gsonObject = new com.google.gson.Gson();
We should add _<%=cid%>

2021-07-01 22:25 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_process_data_end.javajet
> +                                    .map(gsonObject::toJson)
We should add _<%=cid%>

2021-07-01 22:31 UTC, bgunics-talend requested changes
Looks good to me. The only issue I see if someone decide to use gsonObject elsewhere and our component would collide with that.

When we submit a job in the log4j logs we can see the jobId printed with service and oauth accounts? (I don't have service account to test.)

2021-07-01 22:31 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jFileUtil.javajet
> +        }
We should have used this kind of approach from the beginning in the components. I really like this.

2021-07-02 05:54 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> +                        com.google.gson.Gson gsonObject = new com.google.gson.Gson();
Maybe better name it gsonObject_<%=cid%> ?

2021-07-02 06:12 UTC, dmytrogrygorenko requested changes
Some minor comments.

2021-07-02 06:12 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
> +                        com.google.gson.Gson gsonObject = new com.google.gson.Gson();
Maybe better name it gsonObject_<%=cid%> ?

2021-07-02 07:16 UTC, mbasiuk-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jFileUtil.javajet
> +        }
Is this point resolved? Don't know whether it is a question or a statement)

2021-07-02 07:30 UTC, bgunics-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jFileUtil.javajet
> +        }
It's a compliment! I really really like this!

2021-07-02 07:31 UTC, bgunics-talend approved these changes
LGTM

2021-07-02 07:53 UTC, dmytrogrygorenko approved these changes
LGTM

2021-07-02 10:32 UTC, dmytrogrygorenko approved these changes

2021-07-02 10:38 UTC, bgunics-talend approved these changes
LGTM

2021-07-13 09:26 UTC, dmytrogrygorenko approved these changes

2021-07-14 03:36 UTC, merged