feat(TBD-12824): cleanup Pivotal on components
Talend/tdi-studio-se pull request #6474
Opened 2021-07-29 09:09 UTC by sponomarova

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-08-02 15:03 UTC, lbourgeois requested changes

2021-08-02 15:03 UTC, lbourgeois commented on main/plugins/org.talend.libraries.bonita/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Is this change intended ?

2021-08-02 15:03 UTC, lbourgeois commented on main/plugins/org.talend.libraries.jersey/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Is this change intended ?

2021-08-02 15:03 UTC, lbourgeois commented on main/plugins/org.talend.libraries.saaj/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Is this change intended ?

2021-08-02 15:03 UTC, lbourgeois commented on test/plugins/org.talend.designer.scd.test/targets/.gitignore
> +/org/
Is this change intended ?

2021-08-02 15:03 UTC, lbourgeois commented on --form
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
Wrong commit I guess
Same for 2 other empty files :
--header
--url

2021-08-03 12:37 UTC, lbourgeois approved these changes

2021-08-03 13:31 UTC, firefryy approved these changes
lgtm

2021-08-03 15:05 UTC, merged