fix(TDI-46743): avoid file locking when using "streaming append" feature.
Talend/tdi-studio-se pull request #6764
Opened 2021-10-18 09:20 UTC by dmytrogrygorenko

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-46743

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-10-18 12:47 UTC, ozhelezniak-talend requested changes
Didn't catch why we change code that is related to styles here. 
And I think we should put additional try {} finally {} construction inside finally block

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
> +            try (InputStream fis = new FileInputStream(new File(fileName));
new File() 
looks redundant here. You can use another FileInputStream constructor here

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
> +                 Workbook preWorkbookForAppend =
you can close workbook in the try-catch-with-resourcess too

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
> +                    CellStyle clonedStyle = wb.createCellStyle();
Is it related to the current bug?

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
>              wb.close();
what if wb.close() will fail?

try { } finally {try {} finally}

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
> -      <IMPORT NAME="TALEND_EXCEL" MODULE="talendExcel-1.12-20210908.jar" MVN="mvn:org.talend.components/talendExcel/1.12-20210908" UrlPath="platform:/plugin/org.talend.libraries.excel/lib/talendExcel
Could we upload it to Talend Update instead?

2021-10-18 12:47 UTC, ozhelezniak-talend commented on main/plugins/org.talend.libraries.excel/pom.xml
> -                                    <version>1.12-20210908</version>
to Talend Update?

2021-10-18 16:07 UTC, dmytrogrygorenko commented on main/plugins/org.talend.libraries.excel/pom.xml
> -                                    <version>1.12-20210908</version>
Fixed. Moved to Talend Update.

2021-10-18 17:02 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
>              }
try {
            wb.write(outputStream);
        } finally {
            try {
                wb.close();
            } finally {
                try {
                    if (preWb != null) {
                        preWb.close();
                    }
                } finally {
                    // close at the begining to avoid additiona; try-finallly block
                    if (existedOriginToClone != null) {
                        existedOriginToClone = null;
                    }
                    if (outputStream != null) {
                        outputStream.close();
                    }
                }
            }
        }

2021-10-18 17:03 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
>              }
Similar to the above comment.

2021-10-19 05:56 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
> +                }
Fixed. Order of resources closing was restored.

2021-10-21 06:54 UTC, ozhelezniak-talend approved these changes
lgtm

2021-11-02 13:07 UTC, merged