fix(TDI-46912): tELTOutput cannot locate & drop existing table in Snowflake
Talend/tdi-studio-se pull request #6860
Opened 2021-11-01 12:22 UTC by dmytrogrygorenko

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-46912

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-11-08 14:35 UTC, dmytro-sylaiev requested changes

2021-11-08 14:35 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> +            String table = tableName;
I think it's better to just rename variable on the line#61, isn't it?

2021-11-08 14:35 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
> +                            break;
code duplication with `else if (MYSQL.equalsIgnoreCase(dbmsId) || SINGLESTORE.equalsIgnoreCase(dbmsId)`, is it possible to move the fetching property from connection component part to the beginning of the javajet (and use same variable name then)

2021-11-08 14:35 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
> +                            table_<%=cid%> = "\"" + rsTable_<%=cid%>.getString("TABLE_NAME") + "\"";
why do you wrap every tableName to compare in the resultSet instead of just removing wrapping from the `<%=table%>`

2021-11-08 14:37 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> +            String table = tableName;
Wait, does this change break the `useDifferentTable` runtime? Could you please recheck?

2021-11-08 16:28 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> +            String table = tableName;
To be discussed.

2021-11-09 12:06 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> +            String table = tableName;
Made some changes.

2021-11-09 14:14 UTC, dmytro-sylaiev approved these changes

2021-11-09 14:15 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
> +                            break;
nevermind

2021-11-22 10:58 UTC, dmytro-sylaiev approved these changes

2021-11-22 10:59 UTC, merged