feat(TDI-46151): Filter data based on return value in subquery in source database before pushing it down to a tDBInput to execute
Talend/tdi-studio-se pull request #6906
Opened 2021-11-18 11:50 UTC by Tanya5091

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-12-07 10:52 UTC, pyzhou-talend requested changes

2021-12-07 10:52 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_java.xml
> +    <RETURN NAME="QUERY" TYPE="String" AVAILABILITY="AFTER"/>
I think the type should be id_String here

2021-12-07 10:52 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
> +    if(previousNode != null) {
Better to keep clean logic in javajet, as javajet itself is mysterious enough.
if(previousNode != null) {
    if(!dryRun){
//code
}else{
//code
}
}

2021-12-08 02:24 UTC, pyzhou-talend submitted a review, later dismissed
LGTM

2021-12-23 13:36 UTC, olhava commented on main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
> +		String query_<%=cid%> = null;
Maybe need to initialize this variable in any case? (Not only if the check with incoming connections is true)

2021-12-23 13:56 UTC, olhava approved these changes

2021-12-23 15:23 UTC, Tanya5091 commented on main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
> +		String query_<%=cid%> = null;
Okay, sounds right

2021-12-24 10:22 UTC, olhava approved these changes

2021-12-29 15:24 UTC, ypiel-talend approved these changes
LGTM

2022-01-12 15:11 UTC, merged