fix(TDI-35717): tOracleBulkExec's action on table still used when inv…
Talend/tdi-studio-se pull request #7114
Opened 2022-01-13 11:58 UTC by dochkas-talend

…isible

Added additional if wrappers to the sections where data action is processed in tOracleBulkExec_begin.javajet and tOracleBulkExec_end.javajet. The wrappers check if .ctl file or manual .ctl code is used and if so no data action has to be processed

2022-01-13 12:39 UTC, dmytro-sylaiev approved these changes
LGTM

2022-01-14 14:35 UTC, ozhelezniak-talend requested changes
Please, explain \comment
final Process process_<%=cid %> = Runtime.getRuntime().exec(command_<%=cid %>);

2022-01-14 15:06 UTC, dochkas-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
> +	final Process process_<%=cid %> = Runtime.getRuntime().exec(command_<%=cid %>);
Yes, because we need to execute sqlldr command in any case either when we are using .ctl file or when we generate it in Talend Studio

2022-01-14 15:06 UTC, dochkas-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
> +	final Process process_<%=cid %> = Runtime.getRuntime().exec(command_<%=cid %>);
This line ensures that sqlldr command will be executed when we are using .ctl file

2022-01-14 15:10 UTC, dochkas-talend commented
Btw, I noticed a little bug. I forgot to log information when sqlldr command is executed on line 675

2022-01-14 16:03 UTC, ozhelezniak-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
> +	final Process process_<%=cid %> = Runtime.getRuntime().exec(command_<%=cid %>);
okay, thank you

2022-01-14 16:04 UTC, ozhelezniak-talend submitted a review, later dismissed
looks ok

2022-01-19 09:22 UTC, dmytro-sylaiev approved these changes

2022-01-28 09:19 UTC, dmytro-sylaiev approved these changes
Still LGTM

2022-01-28 09:45 UTC, merged