feat(TDI-45870): checkbox in tWriteJSONField to avoid use of scientific notation for float values.
Talend/tdi-studio-se pull request #7183
Opened 2022-02-04 08:34 UTC by dmytrogrygorenko

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45870

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-03-04 14:16 UTC, clesaec requested changes
I think you should add a unit test because it seems that jsonArray.element(Object) method doesn't accept BigDecimal.

2022-03-04 14:16 UTC, clesaec commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +               jsonArray.element(processFloatValues(element));
According to j[sonArray.element(Object) function](http://json-lib.sourceforge.net/apidocs/net/sf/json/JSONArray.html#element(java.lang.Object))
`The value should be a Boolean, Double, Integer, JSONArray, JSONObject, JSONFunction, Long, String, JSONString or the JSONNull object. `
(Can't be a bigdecimal)

2022-03-04 14:16 UTC, clesaec commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +           return new BigDecimal(element.getValue());
This short unit test : 
```java
    @Test
    public void testBigDec() {
        Double x = 0.000004d;
        BigDecimal decimal = BigDecimal.valueOf(45522l, 11);
        System.out.println("x = "  + x);
        System.out.println("decimal = "  + decimal);
    }
```
display : 
```
x = 4.0E-6
decimal = 4.5522E-7
```
with scientific notation
(should use BigDecimal.toPlainString method to see 0.00000045522)

2022-03-07 14:42 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +           return new BigDecimal(element.getValue());
Cannot use BigDecimal.toPlainString(), because the result will be returned as String in output JSON, and customer does not want this. Quote from ticket description:
`The customer use case requires the JSON attribute 'Amount' value will be of type BigDecimal/double (no doubles quotes, refer image below) AND it will have non-scientific notation.`

2022-03-07 14:45 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +               jsonArray.element(processFloatValues(element));
Although it is not mentioned, BigDecimal seems to be working. Here's the output results:
Without scientific notation (Amount is bigDecimal):
`{"Company":"AAA","Name":"Raj","Project":"GIW","Application":"CFW","Amount":"36403807.32"}`
With scientific notation (Amount is Double):
`{"Company":"AAA","Name":"Raj","Project":"GIW","Application":"CFW","Amount":3.640380732E7}`

2022-03-07 14:46 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +               jsonArray.element(processFloatValues(element));
I will try to find how BigDecimal is currently being processed in the code.

2022-03-08 12:26 UTC, dmytrogrygorenko commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +               jsonArray.element(processFloatValues(element));
Final processing of a value goes in this a bit strange method:
https://github.com/Talend/tdi-studio-se/blob/7b5b26f3259acf10d70036335be5c89baa309337/main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/JSONObject.java#L2578-L2605
It works the same way with the Double and BigDecimal values. So, I guess, support of BigDecimal may be just undocumented, but it is present.

2022-03-08 13:35 UTC, clesaec commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +               jsonArray.element(processFloatValues(element));
Yes, [code accept all number class](https://github.com/Talend/tdi-studio-se/blob/7b5b26f3259acf10d70036335be5c89baa309337/main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONUtils.java#L332) =>  `Number.class.isAssignableFrom( clazz )` (and [here](https://github.com/Talend/tdi-studio-se/blob/7b5b26f3259acf10d70036335be5c89baa309337/main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONUtils.java#L348)); 
But [do nothing with](https://github.com/Talend/tdi-studio-se/blob/7b5b26f3259acf10d70036335be5c89baa309337/main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/util/JSONUtils.java#L652-L667) "BigDecimal" ...strange, but that's OK

2022-03-08 13:40 UTC, clesaec commented on main/plugins/org.talend.designer.components.libs/libs_src/json-lib-talend/src/main/java/net/sf/json/xml/XMLSerializer.java
> +           return new BigDecimal(element.getValue());
ok, later, if customer want a plain string for all possible BigDecimal, you'll have to write a sub class of BigDecimal with toString method calling toPlainString

2022-03-08 13:40 UTC, clesaec approved these changes
LGTM

2022-05-06 12:14 UTC, clesaec approved these changes
LGTM

2022-05-06 12:21 UTC, merged