fix(TDI-47519): Kafka ssl conflict with schema registry
Talend/tdi-studio-se pull request #7325
Opened 2022-03-18 19:02 UTC by olhava

* add migration task

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-03-23 12:54 UTC, Tanya5091 approved these changes
LGTM

2022-03-23 12:56 UTC, Tanya5091 submitted a review, later dismissed

2022-03-24 21:15 UTC, Tanya5091 approved these changes

2022-03-25 09:36 UTC, Tanya5091 approved these changes

2022-03-28 22:56 UTC, Tanya5091 approved these changes

2022-05-06 08:44 UTC, ozhelezniak-talend requested changes

2022-05-06 08:44 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SetKeystoreKafkaMigrationTask.java
> +                modified = ModifyComponentsAction.searchAndModify(item, processType, componentFilter,
modified |=

2022-05-06 08:44 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SetKeystoreKafkaMigrationTask.java
> +                modified = ModifyComponentsAction.searchAndModify(item, processType, componentFilter,
in tree places

2022-05-06 08:58 UTC, ozhelezniak-talend submitted a review, later dismissed
lgtm

2022-05-06 09:32 UTC, Tanya5091 submitted a review, later dismissed

2022-05-09 10:16 UTC, ozhelezniak-talend approved these changes
lgtm

2022-05-09 10:18 UTC, merged