fix(TDI-47879): Removed destination property from tExtractJSONFields
Talend/tdi-studio-se pull request #7489
Opened 2022-05-03 08:58 UTC by dochkas-talend

Removed property and added migration task to remove this property from old jobs

2022-05-03 09:57 UTC, ozhelezniak-talend requested changes
migration task should be modified. 
If the Migration task doesn't change anything it should return nothing to do.

2022-05-03 09:57 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveDestinationPropertyExtractJSONFieldsMigrationTask.java
> +            ModifyComponentsAction.searchAndModify(item, processType,
You should use the return value to check if smth was modified.

2022-05-03 09:57 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/plugin.xml
> +              breaks="8.0.1"
Not sure, maybe we need to use 8.0.0 here. Need to ask in tup-tdi.

2022-05-03 11:16 UTC, dochkas-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveDestinationPropertyExtractJSONFieldsMigrationTask.java
> +            ModifyComponentsAction.searchAndModify(item, processType,
Ok, then I should also update my migration task from TDI-47539

2022-05-03 11:59 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveDestinationPropertyExtractJSONFieldsMigrationTask.java
> +            ModifyComponentsAction.searchAndModify(item, processType,
in the scope of another work item

2022-05-04 09:42 UTC, ozhelezniak-talend requested changes

2022-05-04 09:42 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/plugin.xml
> +              breaks="8.0.1"
Could you align tags?

2022-05-04 09:42 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/EncryptClientSecretMicrosoftCRMMigrationTask.java
> +                modified = modified || ModifyComponentsAction.searchAndModify(item, processType,
|| is a bad choice here.

2022-05-04 09:42 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/EncryptClientSecretMicrosoftCRMMigrationTask.java
> +                modified = modified || ModifyComponentsAction.searchAndModify(item, processType,
Also, I asked for a separate WorkItem. Don't mess with different changes for different tickets.

2022-05-04 10:14 UTC, ozhelezniak-talend approved these changes
lgtm

2022-05-04 10:14 UTC, ozhelezniak-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RemoveDestinationPropertyExtractJSONFieldsMigrationTask.java
> +                    componentFilter, Arrays.asList(removeDestinationProp));
You could use here Collections.singletonList

2022-05-19 07:39 UTC, merged