feat(TDI-46737):print jobinfo log
Talend/tdi-studio-se pull request #7618
Opened 2022-06-06 14:17 UTC by pyzhou-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-46737

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-06-07 02:30 UTC, jzhao-talend approved these changes
LGTM

2022-07-11 08:54 UTC, bgunics-talend requested changes

2022-07-11 08:54 UTC, bgunics-talend commented on main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
> +                log.debug("Read jobInfo.properties file fail: " + e.getMessage());
What if log4j is disabled?

2022-07-11 08:54 UTC, bgunics-talend commented on main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
> +		log.warn("Project name: {}\nJob name: {}\nGIT Commit ID: {}\nTalend Version: {}",projectName,jobName,properties.getProperty("gitCommitId"), "<%=System.getProperties().getProperty("talend.studio.ver
Should be info level if log4j is enabled.

2022-07-18 05:09 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
> +                log.debug("Read jobInfo.properties file fail: " + e.getMessage());
fixed, thanks

2022-07-26 03:01 UTC, jzhao-talend approved these changes
LGTM

2022-07-26 03:01 UTC, merged