Vyu/tdi 44761 algorithms support by sftp
Talend/tdi-studio-se pull request #7728
Opened 2022-07-06 09:59 UTC by vyu-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-44761

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-44761

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-07-06 10:26 UTC, pyzhou-talend requested changes

2022-07-06 10:27 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/sftp_connect.javajet
> +class JschLogger implements com.jcraft.jsch.Logger {
Maybe <%=cid%> is needed

2022-07-06 12:21 UTC, pyzhou-talend approved these changes

2022-07-07 10:07 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/sftp_connect.javajet
> +    public void log(int level, String message){
no need to consider the level here?

2022-07-14 07:21 UTC, jzhao-talend commented on main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/AddClientParamsToFTPTDI44761.java
> +                            	boolean useSFTP = "true".equals(ComponentUtilities.getNodePropertyValue(node, "SFTP"));
when "use an existing connection" is checked in tftpget/delete/... 
this migration doesn't need to be applied.

2022-07-14 08:51 UTC, merged