feat(TDI-47508): aws-java-sdk to bundle and CVE update
Talend/tdi-studio-se pull request #7913
Opened 2022-08-23 15:13 UTC by dochkas-talend

overwrite version of aws-java-sdk-* libs

2022-08-23 17:08 UTC, dmytro-sylaiev requested changes

2022-08-23 17:08 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.libs/libs_src/talend-aws/pom.xml
> +			<version>1.12.285</version>
Need to bump also the `talend-aws` lib version and update it where it is used, otherwise could be a conflict

2022-08-26 17:00 UTC, dmytro-sylaiev approved these changes
LGTM

2022-09-01 14:28 UTC, dmytrogrygorenko approved these changes
LGTM

2022-09-02 08:53 UTC, dmytro-sylaiev approved these changes

2022-09-06 14:28 UTC, closed without merging