Vyu/tdi 48213 improve stream closing code m
Talend/tdi-studio-se pull request #7922
Opened 2022-08-31 08:46 UTC by vyu-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-48213

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-48213

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-08-31 10:03 UTC, pyzhou-talend approved these changes
LGTM

2022-08-31 10:04 UTC, pyzhou-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_finally.javajet
> +		}catch(java.lang.Exception e_reader_<%=cid%>) {
Do we really need java.lang.Exception here? ：）

2022-08-31 11:40 UTC, coheigea commented on main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
> +                resourceMap.put("out_<%=cid%>", out<%=cid%>);
Are we missing a finally file for tFileOutputDelimited that guarantees the closure of out_?

2022-09-01 01:22 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
> +                resourceMap.put("out_<%=cid%>", out<%=cid%>);
The closure of out_ has already been involved in [tFileOutputDelimited_finally.javajet](https://github.com/Talend/tdi-studio-se/blob/7d79ca27badec5520a8f34d46d1f6128e70822f9/main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_finally.javajet#L67-L68).

2022-09-01 02:26 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_finally.javajet
> +		}catch(java.lang.Exception e_reader_<%=cid%>) {
Discussed with @jzhao-talend, that the try/catch is not needed, so removed.

2022-09-01 06:08 UTC, coheigea submitted a review, later dismissed

2022-09-14 07:17 UTC, jzhao-talend requested changes

2022-09-14 07:17 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
> +		boolean configureRatio = ("true").equals(ElementParameterParser.getValue(node,"__CONFIGURE_COMPRESSION_RATIO__"));
please revert the wrong commit.

2022-09-14 07:20 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
> +		boolean configureRatio = ("true").equals(ElementParameterParser.getValue(node,"__CONFIGURE_COMPRESSION_RATIO__"));
@jzhao-talend Will do it, many thanks!

2022-09-14 09:53 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_end.javajet
> -if(!(filename_<%=cid %> instanceof java.io.InputStream)){
why remove this part of code ?

2022-09-14 09:56 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_end.javajet
> -if(!(filename_<%=cid %> instanceof java.io.InputStream)){
this part of code is moved to finally part

2022-09-15 08:32 UTC, jzhao-talend approved these changes
LGTM

2022-09-15 08:33 UTC, merged