fix(TDI-49026):close stream.
Talend/tdi-studio-se pull request #8343
Opened 2022-12-23 10:04 UTC by vyu-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-49026

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-49026

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-12-23 10:20 UTC, wwang-talend requested changes

2022-12-23 10:20 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +						resourceMap.put("in_<%=cid %>", in_<%=cid %>);
seems the in_<%=cid %> stream is created in 3 places, why not change the two place?

2022-12-23 10:23 UTC, wwang-talend commented
also the jira show another issue : we generate some never used code, could you fix it?

2022-12-27 01:53 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +					byteReader_<%=cid %> = new org.talend.fileprocess.delimited.RowParserByByte(String.valueOf(filename_<%=cid %>), rowLength_<%=cid %>);
why change this part which filename can be a java.io.InputStream

2022-12-27 06:14 UTC, wwang-talend requested changes

2022-12-27 06:14 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +							resourceMap.put("in_<%=cid %>", in_<%=cid %>);
yes, tfileinputpositinal have another issue:
it will close the streaming input, but before current issue, it exists already, not advice to consider it together here, even without current fix, that streaming input will be close in the wrapped reader object.

so advice to not treat different for streaming iput, just do the same like file path.

Also for the compressed file or streaming input, you don't treat them different, why do different here, not make thing complex, here only do one thing now.

2022-12-27 06:14 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +					byteReader_<%=cid %> = new org.talend.fileprocess.delimited.RowParserByByte(String.valueOf(filename_<%=cid %>), rowLength_<%=cid %>);
why remove the "if(uncompress)" part? "zis_<%=cid %>" streaming object may come from file path, is possible.

2022-12-27 06:16 UTC, wwang-talend requested changes

2022-12-27 06:16 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +            		in_<%=cid %> = new java.io.BufferedReader(new routines.system.UnicodeReader(new java.io.FileInputStream(String.valueOf(filename_<%=cid %>)), <%=encoding %>));
put it to resourceMap too as don't want to guess the code scan logic.

2022-12-27 06:47 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +					byteReader_<%=cid %> = new org.talend.fileprocess.delimited.RowParserByByte(String.valueOf(filename_<%=cid %>), rowLength_<%=cid %>);
This part is for footer, as I see in the XML file, the footer is available when the input file is compressed.

2022-12-27 06:51 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +            		in_<%=cid %> = new java.io.BufferedReader(new routines.system.UnicodeReader(new java.io.FileInputStream(String.valueOf(filename_<%=cid %>)), <%=encoding %>));
Done

> put it to resourceMap too as don't want to guess the code scan logic, or make it to one line.

2022-12-27 06:51 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
> +							resourceMap.put("in_<%=cid %>", in_<%=cid %>);
Done

> yes, tfileinputpositinal have another issue: it will close the streaming input, but before current issue, it exists already, not advice to consider it together here, even without current fix, that streaming input will be close in the wrapped reader object.
> 
> so advice to not treat different for streaming iput, just do the same like file path.
> 
> Also for the compressed file or streaming input, you don't treat them different, why do different here, not make thing complex, here only do one thing now.

2022-12-27 07:58 UTC, wwang-talend approved these changes

2022-12-29 02:12 UTC, merged