feat(TDI-47760):add nb_line to mssqlrow.
Talend/tdi-studio-se pull request #8563
Opened 2023-03-14 04:14 UTC by vyu-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-47760

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-47760

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-03-15 03:39 UTC, pyzhou-talend approved these changes
LGTM

2023-03-15 03:44 UTC, jzhao-talend requested changes

2023-03-15 03:44 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowBegin.javajet
> +	java.sql.Statement stmt_<%=cid %> = null;
why those 2 generated no matter usePrepareStatement true or false

2023-03-15 03:44 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_java.xml
> +    <RETURN NAME="NB_LINE" TYPE="id_Integer" AVAILABILITY="AFTER"/>
Don't forget add i18n for it

2023-03-15 03:44 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		if("true".equals(propagateRecordset_<%=cid %>)){
why add this to runtime, not code generate scope?

2023-03-15 04:00 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowBegin.javajet
> +	java.sql.Statement stmt_<%=cid %> = null;
Because all of the codes are in the code generation scope no matter pstmt_<%=cid %> or stmt_<%=cid %>, so I need those two parameters' definitions.

2023-03-15 04:02 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		if("true".equals(propagateRecordset_<%=cid %>)){
That would be a little complex to put those codes in code generation scope.

2023-03-15 04:06 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowBegin.javajet
> +	java.sql.Statement stmt_<%=cid %> = null;
because of
https://github.com/Talend/tdi-studio-se/pull/8563/files#diff-c0af0113c58c6a8550ed21e5c52b33a7de1cffaffaa7f74175266528369e22fdR152-R157 ?

2023-03-15 04:17 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		if("true".equals(propagateRecordset_<%=cid %>)){
this can't work ?
```
		int count_<%=cid %> = 0;

<%
			if(("true").equals(propagateRecordset)){
%>

				if(rs_<%=cid %> != null){
					while(rs_<%=cid %>.next()){
						count_<%=cid %>++;
					}
				}
<%
			}
%>
		}else{
			java.sql.ResultSet rsMulti_<%=cid %> = null;
			int rsCount_<%=cid %> = -1;
<%
			if(("true").equals(usePrepareStatement)){
%>
				java.sql.Statement commonSt_<%=cid %> = pstmt_<%=cid %>;
<%
			}else{
%>
				java.sql.Statement commonSt_<%=cid %> = stmt_<%=cid %>;
<%
			}
%>
			do {
			    if (isResultSet_<%=cid %>) {
			        if(rsMulti_<%=cid %> != null){
						while(rsMulti_<%=cid %>.next()){
							count_<%=cid %>++;
						}
					}
			    } else {
			    	rsCount_<%=cid %> = commonSt_<%=cid %>.getUpdateCount();
			        if (rsCount_<%=cid %> > 0) {
			            count_<%=cid %> += commonSt_<%=cid %>.getUpdateCount();
			        }
			    }
			    isResultSet_<%=cid %> = commonSt_<%=cid %>.getMoreResults();
			    if (isResultSet_<%=cid %>) rsMulti_<%=cid %> = commonSt_<%=cid %>.getResultSet();
			} while (isResultSet_<%=cid %> || rsCount_<%=cid %> != -1);
		}
		globalMap.put("<%=cid%>_NB_LINE", count_<%=cid %>);
```

2023-03-15 07:43 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		if("true".equals(propagateRecordset_<%=cid %>)){
OK, I'll git it a try.

2023-03-15 08:28 UTC, vyu-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		if("true".equals(propagateRecordset_<%=cid %>)){
Thanks, I've committed the updates, please help to review.

2023-03-15 08:44 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
>  		String propagateRecordset_<%=cid %> = "<%=propagateRecordset %>";
this should also be changed, please see my last code script

updated the script
```
		int count_<%=cid %> = 0;

<%
		if(("true").equals(propagateRecordset)){
%>

				if(rs_<%=cid %> != null){
					while(rs_<%=cid %>.next()){
						count_<%=cid %>++;
					}
				}
<%
		}else{
%>
		
			java.sql.ResultSet rsMulti_<%=cid %> = null;
			int rsCount_<%=cid %> = -1;
<%
			if(("true").equals(usePrepareStatement)){
%>
				java.sql.Statement commonSt_<%=cid %> = pstmt_<%=cid %>;
<%
			}else{
%>
				commonSt_<%=cid %> = stmt_<%=cid %>;
<%
			}
%>
			do {
			    if (isResultSet_<%=cid %>) {
			        if(rsMulti_<%=cid %> != null){
						while(rsMulti_<%=cid %>.next()){
							count_<%=cid %>++;
						}
					}
			    } else {
			    	rsCount_<%=cid %> = commonSt_<%=cid %>.getUpdateCount();
			        if (rsCount_<%=cid %> > 0) {
			            count_<%=cid %> += commonSt_<%=cid %>.getUpdateCount();
			        }
			    }
			    isResultSet_<%=cid %> = commonSt_<%=cid %>.getMoreResults();
			    if (isResultSet_<%=cid %>) rsMulti_<%=cid %> = commonSt_<%=cid %>.getResultSet();
			} while (isResultSet_<%=cid %> || rsCount_<%=cid %> != -1);
<%
		}
%>
		globalMap.put("<%=cid%>_NB_LINE", count_<%=cid %>);
```

2023-03-15 10:07 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
> +		globalMap.put("<%=cid%>_NB_LINE", count_<%=cid %>);
one question about this, here the var set in main part.
and if the tdbrow work as output component and it have more than one rows from input.
how the count work?

2023-03-16 03:42 UTC, jzhao-talend commented on main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_main.javajet
> -if(("true").equals(propagateRecordset)){
why remove this condition?

2023-03-29 07:47 UTC, merged